### PR TITLE
pdo pgsql fix for nested transaction

### PR DESCRIPTION
**Pull request by alikon**
with this fix i'm able  to:

-  install a site
-  create & delete a category (ie item that use nested transactions)
-  install a multilaguage site,  (multilanguage sites btw still have multiple issues)

### CODE REVIEW

**Comment by mbabker** [comment]
... so why does the PDO API fail on transactions here?

**Comment by alikon** [comment]
it doesn't keep track of nested transaction....

**Comment by mbabker** [comment]
Merging for now just to get this thing released, but I've looked at how Doctrine deals with nested transaction management and I think I've got an idea how to iterate on top of this to make things behave consistently.

**Comment by alikon** [comment]
thanks

**Pull request merged**
